import { describe, expect, it } from 'vitest';
import { gzipSync, gunzipSync } from 'fflate';
import { optimize } from 'svgo/browser';
import { optimizeExtreme } from '@/features/svg-compressor/lib/extreme';
import { buildSvgoConfig } from '@/features/svg-compressor/lib/presets';
import { gzipSvgText, readSvgText, svgOutputName } from '@/features/svg-compressor/lib/svgFile';
import type { SvgPreset } from '@/features/svg-compressor/lib/types';

const BLOATED = `<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by test -->
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
  <metadata>Created with some editor</metadata>
  <g id="g1" fill="#ffffff" stroke="rgb(0, 0, 0)">
    <path d="M 10 10 L 90 10 L 90 90 L 10 90 Z"/>
    <circle cx="50.000" cy="50.000" r="10.000"/>
  </g>
</svg>`;

describe('SVGO 预设', () => {
  for (const preset of ['high', 'balanced', 'extreme'] as SvgPreset[]) {
    it(`${preset}：输出更小且不含注释/元数据`, () => {
      const result = optimize(BLOATED, buildSvgoConfig(preset));
      expect(result.data).toContain('<svg');
      expect(result.data).not.toContain('<!--');
      expect(result.data).not.toContain('<metadata');
      expect(result.data.length).toBeLessThan(BLOATED.length);
    });
  }

  it('extreme：长重复路径时启用路径复用且更小', () => {
    const longPath =
      'M1 2c3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70z';
    const paths: string[] = [];
    for (let i = 0; i < 5; i += 1) {
      paths.push(`<path d="${longPath}"/><circle cx="${10 + i * 2}" cy="${10 + i * 2}" r="1"/>`);
    }
    const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">${paths.join('')}</svg>`;
    const extreme = optimizeExtreme(icon, optimize);
    const balanced = optimize(icon, buildSvgoConfig('balanced')).data;
    expect(extreme).toContain('<use');
    expect(extreme.length).toBeLessThan(balanced.length);
  });

  it('extreme：短路径场景不会比 balanced 更大', () => {
    const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M4 4h6v6H4z"/><circle cx="12" cy="12" r="2"/><path d="M4 4h6v6H4z"/></svg>`;
    const extreme = optimizeExtreme(icon, optimize);
    const balanced = optimize(icon, buildSvgoConfig('balanced')).data;
    expect(extreme.length).toBeLessThanOrEqual(balanced.length);
  });
});

describe('SVG 安全净化', () => {
  const DANGEROUS = `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100" onload="alert(1)">
  <script>alert('xss')</script>
  <a href="https://evil.example.com/x"><rect width="20" height="20"/></a>
  <image href="http://evil.example.com/x.png" width="10" height="10"/>
  <rect width="10" height="10" onclick="steal()" style="fill: url(http://evil.example.com/a.png)"/>
  <style>@import url("https://evil.example.com/style.css"); .a{fill:red}</style>
</svg>`;

  for (const preset of ['high', 'balanced', 'extreme'] as SvgPreset[]) {
    it(`${preset}：移除脚本、事件属性、外链与外部样式引用`, () => {
      const result = optimize(DANGEROUS, buildSvgoConfig(preset));
      expect(result.data).not.toContain('script');
      expect(result.data).not.toContain('onload');
      expect(result.data).not.toContain('onclick');
      expect(result.data).not.toContain('javascript:');
      expect(result.data).not.toContain('evil.example.com');
      expect(result.data).not.toContain('@import');
      expect(result.data).not.toMatch(/url\(/);
    });
  }

  it('保留内部引用（不误伤合法内容）', () => {
    const safe = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
  <defs><linearGradient id="g"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#000"/></linearGradient></defs>
  <rect width="10" height="10" fill="url(#g)"/>
  <use href="#g"/>
</svg>`;
    const result = optimize(safe, buildSvgoConfig('balanced'));
    expect(result.data).toMatch(/url\(#/);
    expect(result.data).toMatch(/href="#/);
  });
});

describe('SVG 文件处理', () => {
  it('gzip 往返一致', () => {
    const text = '<svg xmlns="http://www.w3.org/2000/svg"/>';
    const gz = gzipSvgText(text);
    expect(gunzipSync(gz)).toEqual(new TextEncoder().encode(text));
  });

  it('readSvgText 自动解压 svgz 输入', async () => {
    const text = '<svg xmlns="http://www.w3.org/2000/svg"><circle cx="1" cy="2" r="3"/></svg>';
    const file = new File([gzipSync(new TextEncoder().encode(text))], 'icon.svgz');
    await expect(readSvgText(file)).resolves.toBe(text);
  });

  it('普通 svg 输入不解压', async () => {
    const text = '<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10"/></svg>';
    const file = new File([text], 'icon.svg');
    await expect(readSvgText(file)).resolves.toBe(text);
  });

  it('输出文件名与输入一致，格式转换时更换扩展名', () => {
    expect(svgOutputName('icon.svg', 'svg')).toBe('icon.svg');
    expect(svgOutputName('icon.SVGZ', 'svgz')).toBe('icon.SVGZ');
    expect(svgOutputName('icon.svg', 'svgz')).toBe('icon.svgz');
    expect(svgOutputName('icon.svgz', 'svg')).toBe('icon.svg');
  });
});
